### ISSUE TITLE
Can't seem to figure it out 

### ISSUE THREAD

**Issue by skasas0** [stegripe/discord-chat-mirror#288]
Keep getting this error 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @stegripe/eslint-config@1.0.1
npm ERR! Found: eslint-plugin-import-x@4.6.1
npm ERR! node_modules/eslint-plugin-import-x
npm ERR!   peerOptional eslint-plugin-import-x@"*" from eslint-import-resolver-typescript@3.7.0
npm ERR!   node_modules/eslint-import-resolver-typescript
npm ERR!     peer eslint-import-resolver-typescript@"^3.6.1" from @stegripe/eslint-config@1.0.1
npm ERR!     node_modules/@stegripe/eslint-config
npm ERR!       dev @stegripe/eslint-config@"1.0.1" from the root project
npm ERR!   dev eslint-plugin-import-x@"^4.6.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-import-x@"^3.0.1" from @stegripe/eslint-config@1.0.1
npm ERR! node_modules/@stegripe/eslint-config
npm ERR!   dev @stegripe/eslint-config@"1.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint-plugin-import-x@3.1.0
npm ERR! node_modules/eslint-plugin-import-x
npm ERR!   peer eslint-plugin-import-x@"^3.0.1" from @stegripe/eslint-config@1.0.1
npm ERR!   node_modules/@stegripe/eslint-config
npm ERR!     dev @stegripe/eslint-config@"1.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Tiramitzu** [comment]
For now use flag --force or --legacy-peer-deps, ill fix it later

**Comment by skasas0** [comment]
> discord-chat-mirror@2.0.0 build
> npm run lint && npm run compile


> discord-chat-mirror@2.0.0 lint
> eslint . --cache --cache-file .eslintcache


> discord-chat-mirror@2.0.0 compile
> tsc --build tsconfig.json


> discord-chat-mirror@2.0.0 start
> node --env-file .env --es-module-specifier-resolution=node .

node: bad option: --env-file

**Comment by skasas0** [comment]
shortly after

**Comment by skasas0** [comment]
![image](https://github.com/user-attachments/assets/6391a8ff-9416-45b4-bc95-556be1cb01b7)

**Comment by skasas0** [comment]
![Capture](https://github.com/user-attachments/assets/36152a5f-3ccc-4a8c-bff8-e07ee3207cb0)

**Comment by Tiramitzu** [comment]
what nodejs version are you using?

**Comment by skasas0** [comment]
v18.14.2

**Comment by Tiramitzu** [comment]
seems like nodejs 18 cant load .env using the --env-file flag yet, maybe try using nodejs 20 or 19

**Comment by skasas0** [comment]
Worked any way to clone a whole server rather than doing it one by one ?

**Comment by Tiramitzu** [comment]
for now, no
